@startuml Context Demo

title C4 Context Diagram

!include <C4/C4_Context>
!include <C4/C4_Container>

LAYOUT_WITH_LEGEND()

Person(user, "App User")
Person(recipient, "Gift Recipient")

Container(app, "Hey Lemonade App", "React Native")

Container(gifts, "Gifts Site", "React, S3, CloudFront", "Pep Playback for Gift Recipients")
Container(redeem, "Code Redemption Site", "React, S3, CloudFront", "Redeem physical gift card codes")

Rel(user, app, "Uses")
Rel(user, redeem, "Uses")

Rel_R(user, recipient, "Shares")

Rel(recipient, gifts, "Uses")

@enduml